on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * 1-5"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}


  
jobs:
  indepth-analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: indepth-analysis.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 4
          plugin_languages_analysis_timeout: 15
  Full-year-calendar:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - uses: lowlighter/metrics@latest
          with:
            filename: fullyear-calendar.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_isocalendar: yes
            plugin_isocalendar_duration: full-year


